### ISSUE TITLE
продумать главную страницу, ее оформление, дизайн

### ISSUE THREAD

**Issue by ParilovaAleksandra** [ParilovaAleksandra/TRPO2#10]

**Comment by ISextra** [comment]
Поиск различных изображений для фона на сайте [Pixels](https://www.pexels.com/ru-ru/)

[123.zip](https://github.com/ParilovaAleksandra/TRPO2/files/4732821/123.zip)

**Comment by ISextra** [comment]
подбор различных цветовых палитр для фона

**Comment by ISextra** [comment]
оканчательный выбор палитры и фона
светло серый фон - 
![white-painted-wall-1939485](https://user-images.githubusercontent.com/61829552/83809621-73346780-a6bf-11ea-8d13-ab553dc0840c.jpg)
