### ISSUE TITLE
продумать идею проекта, утвердить задачи 

### ISSUE THREAD

**Issue by ParilovaAleksandra** [ParilovaAleksandra/TRPO2#12]

**Comment by VladPodobin** [comment]
Идея проекта- информационный сайт с тестами по географическим объектам
В дальнейшем планируется расширение до каких- либо интересных фактов, возможны новые разделы

**Comment by SanyaSkryabin** [comment]
Идея проекта была расширена. Мы решили добавить еще 2 раздела: Игры, Искусство.В начале этой недели по данным разделам были составлены вопросы и подобраны картинки/фото для оформления.

**Comment by SanyaSkryabin** [comment]
Вышесказанное оформлено в других задачах.
