### ISSUE TITLE
прорисовать карту

### ISSUE THREAD

**Issue by ParilovaAleksandra** [ParilovaAleksandra/TRPO2#13]

**Comment by SanyaSkryabin** [comment]
При помощи фотошопа вырезал карту, которую мы выбрали всей командой и которая подходит к нам по стилю в пнг формате:
![карта](https://user-images.githubusercontent.com/61835045/83249254-fed56200-a1ae-11ea-9a28-d44d8d30cb17.png)
После команда меня попросила разделить карту на континенты, что я и сделал, нашел все континенты вырезал отдельно антарктиду и соединил в одну карту. 
![image](https://user-images.githubusercontent.com/61835045/83249784-c6825380-a1af-11ea-9e7d-e551c66f9409.png)
