### ISSUE TITLE
Найти картинки для вопросов теста по Африке, Северной Америке, Евразии

### ISSUE THREAD

**Issue by VladPodobin** [ParilovaAleksandra/TRPO2#15]

**Comment by SanyaSkryabin** [comment]
Для каждого из вопросов нашёл по 2 картинки(1 для вопроса, 1 для ответа) примерно под одну стилистику и в формате >1920x1080 для простоты использования программистом. Поскольку зип нельзя загрузить приложу скрины:
![image](https://user-images.githubusercontent.com/61835045/83250839-65f41600-a1b1-11ea-99bf-0a9518658466.png)
![image](https://user-images.githubusercontent.com/61835045/83250873-6f7d7e00-a1b1-11ea-8f7f-ac8aab9a7029.png)
![image](https://user-images.githubusercontent.com/61835045/83250900-7906e600-a1b1-11ea-90dc-06b5aaff7561.png)
