### ISSUE TITLE
Найти картинки к вопросам из тестов по компьютерным играм(2)

### ISSUE THREAD

**Issue by VladPodobin** [ParilovaAleksandra/TRPO2#19]

**Comment by SanyaSkryabin** [comment]
Подобрал картинки на фон для вопросов(не очевидные) и ответов(очевидные) по играм используя бесплатные источники в интернете.
![Uploading image.png…]()

**Comment by SanyaSkryabin** [comment]
![image](https://user-images.githubusercontent.com/61835045/83254130-ebc69000-a1b6-11ea-8de9-ee372afe9d54.png)
