### ISSUE TITLE
найти и проанализировать данные по оставшимся трем из материков, составить на основе анализа по 10 интересных вопросов на разные тематики

### ISSUE THREAD

**Issue by ParilovaAleksandra** [ParilovaAleksandra/TRPO2#2]

**Comment by SanyaSkryabin** [comment]
Создал вопросы по 3 континентам используя различные туристические сайты и форумы(Северная Америка, Африка и Антарктида). 
[Вопросы.docx](https://github.com/ParilovaAleksandra/TRPO2/files/4701232/default.docx)

**Comment by SanyaSkryabin** [comment]
Для каждого из вопросов нашёл по 2 картинки(1 для вопроса, 1 для ответа) примерно под одну стилистику и в формате >1920x1080 для простоты использования программистом. Поскольку зип нельзя загрузить приложу скрины:
![image](https://user-images.githubusercontent.com/61835045/83250594-0bf35080-a1b1-11ea-8a16-62e7d5c2f10c.png)
![image](https://user-images.githubusercontent.com/61835045/83250621-1b729980-a1b1-11ea-92dd-214257280362.png)
![image](https://user-images.githubusercontent.com/61835045/83250661-2b8a7900-a1b1-11ea-9ae0-11490247416d.png)
