### ISSUE TITLE
найти и проанализировать данные по трем из материков, составить на основе анализа по 10 интересных вопросов на разные тематики

### ISSUE THREAD

**Issue by ParilovaAleksandra** [ParilovaAleksandra/TRPO2#3]

**Comment by VladPodobin** [comment]
сделал
были составлены вопросы по трем материкам
в итоге 30 вопросов
[voprosiki_po_materikam2_0.docx](https://github.com/ParilovaAleksandra/TRPO2/files/4667300/voprosiki_po_materikam2_0.docx)
